#!/bin/bash -eu

[[ $EUID = 0 ]] || { echo >&2 "Must run as sudo / root"; exit 1; }

basedir="$(dirname "$(readlink -f "$0")")"
servicename=jethro_attendancegroup_refresher@"$ATL_TENANT"

cd /etc/systemd/system
ln -sf "$basedir/jethro_attendancegroup_refresher@.service" "$servicename".service
ln -sf "$basedir/jethro_attendancegroup_refresher@.timer" "$servicename".timer
systemctl daemon-reload
systemctl start "$servicename".timer
if systemctl -q is-enabled "$servicename".timer; then
	echo "$servicename.timer is installed"
else
	echo >&2 "failed to install $servicename.timer"
	exit 1
fi
#systemctl list-timers jethro\*
